// action types
export const ACTIVE_FILTER = 'ACTIVE_FILTER';

export const ADD_GOAL = 'ADD_GOAL';
export const GET_GOALS = 'GET_GOALS';

export const EDIT_GOAL = 'EDIT_GOAL';
export const EDIT_GOAL_TITLE_CHANGED = 'EDIT_GOAL_TITLE_CHANGED';
export const EDIT_GOAL_TEXT_CHANGED = 'EDIT_GOAL_TEXT_CHANGED';
export const EDIT_GOAL_RANGE_FROM_CHANGED = 'EDIT_GOAL_RANGE_FROM_CHANGED';
export const EDIT_GOAL_RANGE_TO_CHANGED = 'EDIT_GOAL_RANGE_TO_CHANGED';
export const EDIT_GOAL_COMPLETED_CHANGED = 'EDIT_GOAL_COMPLETED_CHANGED';
export const REMOVE_GOAL = 'REMOVE_GOAL';

export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const SELECT_PARTICIPANT = 'SELECT_PARTICIPANT';

// filters for goals
export const FILTER_NONE = 'FILTER_NONE';
export const FILTER_COMPLETED = 'FILTER_COMPLETED';